# Class 2, in-class work

Date: Jan. 25,  2018

In [1]:
my_string = "hello world"

In [2]:
print(my_string)

hello world


## Playing with slices

Syntax of a slice: `my_string[start:end]` where `end` is not inclusive.

In [8]:
my_string[0:6]

'hello '

Here is a function to know the length of a string: `len()`

In [9]:
len(my_string)

11

To access the _last_ element, use index `-1`

In [10]:
my_string[-1]

'd'

What's a good way to get all of the characters of `my_string`, except the last one?

In [14]:
my_string[0:-1]

'hello worl'

You can also do slices as: `start:end:step` ... and a `-1` step goes backwards!

In [15]:
my_string[0:len(my_string)]

'hello world'

In [19]:
my_string[::-1]

'dlrow olleh'

## Slicing on NumPy arrays

Arrays are the essential data structure in numerical computing! They are available to you via the `numpy` library. Load the library like this:

In [20]:
import numpy

In [21]:
x = numpy.array([2, 4, 6, 8])

In [22]:
x[0]

2

In [23]:
x[1:3]

array([4, 6])

In [36]:
x = numpy.linspace(0, 100, 26)
print(x)

[   0.    4.    8.   12.   16.   20.   24.   28.   32.   36.   40.   44.
   48.   52.   56.   60.   64.   68.   72.   76.   80.   84.   88.   92.
   96.  100.]


In [37]:
type(x)

numpy.ndarray

In [38]:
type(x[0])

numpy.float64

In [29]:
x[3:12]

array([ 12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,  44.])

In [30]:
?numpy.arange

In [39]:
y = numpy.arange(0,100,4)
print(y)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


In [40]:
type(y)

numpy.ndarray

In [41]:
type(y[0])

numpy.int64

### Welcome 2D arrays!

In [42]:
X = numpy.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


From the X array, use indexing to:

* Grab the 2nd element in the 1st column.
* Grab the 2nd element in the 2nd column.
* Grab the first row.
* Grab the first column.

In [44]:
X[0,:]

array([1, 2])

In [43]:
X[:,0]

array([1, 3])